import pandas as pd
import numpy as np
import matplotlib
import epde.interface.interface as epde_alg
import epde.globals as global_var
from epde.evaluators import CustomEvaluator
import os
from epde.interface.prepared_tokens import Custom_tokens, Trigonometric_tokens, Cache_stored_tokens

import matplotlib.pyplot as plt
import torch
import TEDEouS

from TEDEouS import solver
from TEDEouS import config

os.chdir(os.path.dirname(__file__))


def load_data(mesh):
    """
    Loads the wave equation solution data from a CSV file generated by Wolfram Mathematica.
    
        The data represents the numerical solution of a wave equation, pre-computed using Wolfram's NDSolve function.
        This function reads the solution, prepares the spatial and temporal grids, and returns the solution along with the grid parameters.
        This data loading is crucial for training and validating neural network models designed to approximate solutions to differential equations.
        By using pre-computed solutions, we can evaluate the performance of our neural network-based solvers against known, accurate results.
    
        Args:
            mesh (int): The resolution of the spatial and temporal grid used in the Wolfram solution.
                        This determines the size of the CSV file to be loaded.
    
        Returns:
            tuple: A tuple containing:
                - u (numpy.ndarray): The wave equation solution values, with time along the Y-axis and space along the X-axis.
                - grid (list): A list of meshgrid arrays representing the spatial and temporal grid.
                - params (list): A list containing the time and space linspaces used to generate the grid.
    """

    df = pd.read_csv(f'wolfram_sln/wave_sln_{mesh}.csv', header=None)
    u = df.values
    u = np.transpose(u)  # x1 - t (axis Y), x2 - x (axis X)

    t = np.linspace(0, 1, mesh + 1)
    x = np.linspace(0, 1, mesh + 1)
    grid = np.meshgrid(t, x, indexing='ij')
    params = [t, x]

    return u, grid, params


def equation_fit(grid, data):
    """
    Fits an equation to the given data using the EPDE algorithm.
    
        This method leverages the EPDE algorithm to discover differential equations that accurately represent the provided data. By setting up search parameters, defining custom grid tokens relevant to the problem's geometry, and performing the fit, it identifies potential equation candidates. The resulting equations are then converted into a solver-compatible format, enabling their use with neural network-based solvers for differential equations. This process helps in finding suitable differential equation representations that can be effectively solved using neural networks.
    
        Args:
            grid: The coordinate grid for the data.
            data: The data to fit the equation to.
    
        Returns:
            list: A list of tuples, where each tuple contains the solver form of an
                equation and its boundary conditions.
    """
    boundary = 0
    dimensionality = data.ndim

    epde_search_obj = epde_alg.epde_search(use_solver=False, eq_search_iter=100,
                                           dimensionality=dimensionality)

    epde_search_obj.set_memory_properties(data, mem_for_cache_frac=10)
    epde_search_obj.set_moeadd_params(population_size=10, training_epochs=5)

    custom_grid_tokens = Cache_stored_tokens(token_type='grid',
                                             boundary=boundary,
                                             token_labels=['t', 'x'],
                                             token_tensors={'t': grid[0], 'x': grid[1]},
                                             params_ranges={'power': (1, 1)},
                                             params_equality_ranges=None)

    epde_search_obj.fit(data=data, max_deriv_order=(2, 2), boundary=boundary,
                        equation_terms_max_number=3, equation_factors_max_number=1,
                        coordinate_tensors=grid, eq_sparsity_interval=(1e-8, 5.0),
                        deriv_method='poly', deriv_method_kwargs={'smooth': True, 'grid': grid},
                        additional_tokens=[custom_grid_tokens, ],
                        memory_for_cache=25, prune_domain=False)

    res = epde_search_obj.equation_search_results(only_print=False, level_num=2)

    solver_inp = []

    for eq in res[0]:
        solver_inp.append((eq.structure[0].solver_form(), eq.structure[0].boundary_conditions()))

    epde_search_obj.equation_search_results(only_print=True, level_num=1)
    return solver_inp


if __name__ == '__main__':

    grid_res = 50

    u, grid_u, params = load_data(grid_res)

    solver_inp = equation_fit(grid_u, u)

    models = []

    for eqn_n, s_inp in enumerate(solver_inp):
        coord_list = params

        cfg = config.Config()

        cfg.set_parameter("Cache.use_cache", True)
        cfg.set_parameter('Cache.save_always', True)

        principal_bcond_shape=s_inp[1][0][1].shape

        for i in range(len(s_inp[1])):
            s_inp[1][i][1]=s_inp[1][i][1].reshape(principal_bcond_shape)



        model = solver.optimization_solver(coord_list, None, s_inp[0], s_inp[1], cfg, mode='NN')
        print(model)

        models.append(model)






